// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "alex.derakchev",
            "email": "alex.derakchev@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/comments/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Получение комментария по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID искомого комментария",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект с данными комментария",
                        "schema": {
                            "$ref": "#/definitions/model.Comment"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "комемнтарий с таким ID не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка БД",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Изменение комментария",
                "parameters": [
                    {
                        "description": "ID изменяемого комментария",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CommentUpdateRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID изменяемого комментария",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект с данными измененного комментария",
                        "schema": {
                            "$ref": "#/definitions/model.Comment"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "попытка изменить чужой комментарий",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "комментарий с таким ID не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка БД",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен авторизации",
                        "schema": {
                            "$ref": "#/definitions/model.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка подписи токена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/porfile": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Профиль пользователя",
                "responses": {
                    "200": {
                        "description": "объект с данными пользователя",
                        "schema": {
                            "$ref": "#/definitions/model.UserResponse"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "ошибка авторизации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "пользователь не найден в БД",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/posts": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Создание нового поста",
                "parameters": [
                    {
                        "description": "данные нового поста",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PostCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "объект с данными созданного поста",
                        "schema": {
                            "$ref": "#/definitions/model.Post"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "попытка создать пост не авторизовавшись",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка записи в базу данных/кэш",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/posts/author/{authorID}{limit}{offset}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получение списка постов автора с лимитом и пагинацией",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID автора",
                        "name": "authorID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "количество постов на страницу",
                        "name": "limit",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "смещение от начала списка",
                        "name": "offset",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект со списком постов, общим количеством постов лимитом и смещением",
                        "schema": {
                            "$ref": "#/definitions/handler.PostsResponse"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/posts/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получение поста по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID искомого поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект с данными искомого поста",
                        "schema": {
                            "$ref": "#/definitions/model.Post"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "пост с таким ID не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка записи в кэш",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Изменение поста",
                "parameters": [
                    {
                        "description": "ID искомого поста",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PostUpdateRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "ID изменяемого поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект с данными измененного поста",
                        "schema": {
                            "$ref": "#/definitions/model.Post"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "попытка изменить чужой пост",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "пост с таким ID не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка записи в кэш",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "posts"
                ],
                "summary": "Удаление поста",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемого поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "попытка удалить чужой пост",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "пост с таким ID не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/posts/{id}/comments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Создание нового комментария",
                "parameters": [
                    {
                        "description": "данные нового поста",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PostCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "объект с данными созданного поста",
                        "schema": {
                            "$ref": "#/definitions/model.Post"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "попытка создать пост не авторизовавшись",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "не найден пост",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка записи в базу данных",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/posts/{id}/comments{limit}{offset}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Получение комментария по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID искомого поста",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "количество комментариев на страницу",
                        "name": "limit",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "смещение от начала списка",
                        "name": "offset",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект со списком комментариев, общим количеством комментариев лимитом и смещением",
                        "schema": {
                            "$ref": "#/definitions/handler.CommentsResponse"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "комемнтарий с таким ID не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка БД",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/posts{limit}{offset}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Получение списка постов с лимитом и пагинацией",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "количество постов на страницу",
                        "name": "limit",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "смещение от начала списка",
                        "name": "offset",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "объект со списком постов, общим количеством постов лимитом и смещением",
                        "schema": {
                            "$ref": "#/definitions/handler.PostsResponse"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Зарегистрировать нового пользователя",
                "parameters": [
                    {
                        "description": "Парамеры нового пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Токен авторизации",
                        "schema": {
                            "$ref": "#/definitions/model.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "неправильные параметры",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "неподдерживаемый метод",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "пользователь с таким именем уже существует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ошибка записи в базу данных",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CommentsResponse": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Comment"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.PostsResponse": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Post"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Comment": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "post_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.CommentUpdateRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1
                }
            }
        },
        "model.Post": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string",
                    "maxLength": 100000,
                    "minLength": 1
                },
                "created_at": {
                    "type": "string"
                },
                "draft": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "publish_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.PostCreateRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 100000,
                    "minLength": 1
                },
                "publish_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                }
            }
        },
        "model.PostUpdateRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 100000,
                    "minLength": 1
                },
                "publish_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                }
            }
        },
        "model.TokenResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/model.UserResponse"
                }
            }
        },
        "model.UserCreateRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "model.UserLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                }
            }
        },
        "model.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "blog-api",
	Description:      "Back-end для блог-платформы с поддержкой постов и комментариев к ним.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
